### ISSUE TITLE
Uses github.io legacy D&D website to fetch books as pdfs, and pushes them to GetBook.

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#103]
We should first update the books to some standard and style, and move them all over to this repository. I don't want to refer to the old site :)

Shoot some inspirations if you'd like.

![Skyrim](https://github.com/user-attachments/assets/aea02ef9-4cc6-4eb6-bb5a-1463200e7d2a)
![Baldur's Gate 3](https://github.com/user-attachments/assets/6796cd87-ed64-44bd-9c38-2fe7c1e27c65)
![Witcher 3](https://github.com/user-attachments/assets/2cdf9517-4ad5-4ebe-a7ce-26c2db150fa4)
![RPGMaker](https://github.com/user-attachments/assets/ba7b6a22-d312-4b2e-8276-53b6725c28d5)

**Comment by ozgurozbek** [comment]
We can make these like blogposts, which have multiple benefits - not a pdf file, seo, nextjs slugs, etc. Would be easier to update and in the meantime would mean we'd move everything to this repository.

**Comment by god-hephaestus** [comment]
#104 we can discuss changes here

**Comment by ozgurozbek** [comment]
So, what do we do here? @god-hephaestus @kutagorn

Lets say I moved the PDFs, they'll get indexed as well, and not only that we'll still be using the weird and deprecated library for pdf books. My year old PR to that repository still stands active and it looked like a student project then, and hasn't been updated.

Please finalize the trajectory **today**. If not I'll just make a 2 column scrollable area mix like the Witcher screenshot. Not SEO friendly 100%. We can also make them markdowns and whatnot to have separate pages like https://teothe.com/library/what-are-these-clovers, similar to species. Or any other ideas...

**Comment by kutagorn** [comment]
I always liked the way Amnesia handled story snippets, it presents them as readable pages in a stylized way, while still being accessible if you inspect the pagel It's like a blend of visual immersion and computer-readable format. Maybe we could explore something similar, where the content looks visually like a book snippet but is structured for SEO.

I’m not entirely sure how this would impact SEO, though.
![image](https://github.com/user-attachments/assets/3017c038-f578-4e86-9631-9401f1c21def)

**Comment by god-hephaestus** [comment]
Weird library is no longer an option. Because it is weird. We appreciate what it has done for us but it's time to retire it.

I like what @kutagorn has in mind. Seems easy enough as well. One important thing is to handle the text changes in a SEO friendly manner where crawlers can read all the text. Ravenswatch has really cool book-like menus as well. Maybe we can take inspiration.

**Comment by ozgurozbek** [comment]
I wanted to explore a Ravenswatch style UI too but that's waaaay out of scope for us. I mean, at that point if we were to make a page like that, it's better to just change the main layout 😄.

@kutagorn 's idea is fine, so we prefer a cover with text. Sure but what about the library itself? I don't want to load every book into the main page tbh. Let me explore some SEO friendly options

**Comment by ozgurozbek** [comment]
Asked the expert, he says having subpages like species is way better for SEO. We can then add buttons backlinks etc. to them as well. He suggested that it's also a good idea to separate the slug by the library tabs. I still don't know what to do with the library page since we decided to no longer load the books on that page.

**Comment by ozgurozbek** [comment]
![image](https://github.com/user-attachments/assets/b88bf5f3-9573-4f82-b336-0da188b94aa8)
![image](https://github.com/user-attachments/assets/6c7e7cbe-5011-441c-a0a3-c9f229d6f09d)

url is /library/whatever-book-is-loaded

I'm fairly happy with this. Followed the [design doc for library](https://www.figma.com/proto/R8gs41YADmA01ZNXFfPUmJ/Teothe?node-id=168-462) and our ideas basically. What do you think everyone? @kutagorn @god-hephaestus

**Comment by ozgurozbek** [comment]
Mobile

![image](https://github.com/user-attachments/assets/03a5b80e-8085-4f66-a73d-adf2d78cebc4)
![image](https://github.com/user-attachments/assets/821dac0a-cc97-407c-95a4-b1e51236a9df)

**Comment by ozgurozbek** [comment]
I've removed the question tag since the design and component ideating parts of the issue is done. Please help me merge the books. I'd rather have you guys do this once or twice so you are accustomed to these types of pages as well. I also am not sure if this is the best practice way of doing it, so maybe you'll improve somethings. Please, give it a go.

@kutagorn @god-hephaestus
