### ISSUE TITLE
Moving stuff to frontend from AWS for SEO

### ISSUE THREAD

**Issue by god-hephaestus** [ozgurozbek/teothe#104]
let's decide on which pages we want to do SEO to. Then we can decide on how and carry them to FE. Or maybe there is a way to implement some seo-friendly approaches in AWS?

Tabs that we certainly need to move to FE:
- Quest Idea Generator
- Quick NPC Generator
- Species
- Library
- Planes
- Deities: Faerun(?) Deities also need to be added.

Tabs that we move if we think we can do SEO to them:
- Languages
- Pricing
- Calculate Trade: This needs the option to be a generator, which the DMs could use.

Tabs that we probably can leave in AWS:
- Common Lore
- Tables
- Map Overlay
- Calendar
- Tools
- Homebrews
- Achievements
- Map Legend

**Comment by ozgurozbek** [comment]
When it comes to Library as well, we were talking about making it a posts structure. Syntick is okay with helping us out, so we'll have content ready for some months, including our previous entries.

**Comment by god-hephaestus** [comment]
Quest Idea Generator needs traffic the most. Because it is gonna be the money-maker. We're essentially bundling everything up with that to see if we can generate any revenue. Even if it's not the prop itself, the page still needs killer SEO. Even if that means a bunch of new text elements etc. Or if you did something else to achieve traffic we can try that.

Quick NPC Generator similarly needs SEO. I do believe this is a very useful tool. And I think people will use it for longer than Quest Idea Gen per session. %100 needs some sort of traffic. If we achieve to get revenue off of this I have so many upgrades to this in mind as well.

Deities, I thought of adding 5e gods because most 5e sites I know are either too deep in the AI trashpile text or they're in the direction of 20 year old php site with no SSL, initial load takes 2 mins and if you tried you could probably see the database. I don't want to do SEO to compete with the garbage generators. I don't want to fight for the keyword [enter 5e god name] either. We're on the same page here. I'm talking more about deity relations, things that are deity related in general. Keywords where you normally often see forum posts.

Pricing, not even keyword related honestly. If we make a solid structure, I'm sure we can attract traffic. Research (which is the hard part) has already been done.

Calculate Trade seems like a great opportunity to me. Though I agree it needs some work in how it works and what the page is like. After generators, this is one of the pages I see most sleeper potential in alongside pricing. "5e calculate trade gold", "dnd trade gold calculator", "dnd reward gp for travel" and so on. I think this is where next will shine the most. I definitely believe we should give this a go.

And I realize that the header for my issue was "moving stuff from AWS to FE for SEO" but it was mainly a discussion of which pages to work on. Let me know what you think, let's get to planning and open the issues. At the start of next month (or when you're available in your personal life) we can get to it.

**Comment by god-hephaestus** [comment]
Also keep in mind that we can actually make the project not open source. I checked and the way we host things isn't an issue (not 100% sure).

**Comment by ozgurozbek** [comment]
Hosting from GitHub Pages and using actions needs enterprise for it to be private AFAIK. Could you make sure?

**Comment by ozgurozbek** [comment]
https://github.com/ozgurozbek/teothe/issues/104#issuecomment-2412360960 Missed this as a whole apparently, sorry for the delay.

---

Wouldn't it be better to move the QuestIdeaGen itself to a different domain and hosting then? It'll always look more inviting compared to the teothe website if you consider UI UX.

I agree on the Quick NPC Gen. It can be its own project as well, markov chain ML model name generator is already a thing in QuestIdeaGen itself. React one is WAY better of course.

Still a bit confused on Deities, but if you have a vision you are free to descend to SEO goblin again 😄

> If we make a solid structure

It feels like all of our plans boil down to this man. What do? Separate some focus across some network of services? Keeping them all in Teothe could be bad.

---

In all regards, I'll start moving stuff to the frontend slowly. It's easy, just load the page, get response and put it in the page itself.

**Comment by god-hephaestus** [comment]
Specifically about Deities, deities page's deity content and deity/{deityName}'s content can't be the same. Apparently we need to target different keyword and avoid duplications. Or those pages appear as duplicates of the deities page. OR we need to add a lot more to it in some other way.

For QuestIdeaGen we can add static text to the page for initial load that is apart from the generated element and that's pretty much all that I know about this.

I don't see the downside of keeping all services inside teothe. But I also don't feel confident in my knowledge.

Go ahead and open up a branch where you start moving stuff to FE. We'll do other structure adjustments in that branch too. Godspeed.

**Comment by ozgurozbek** [comment]
For deities, we can make the child page canonical, which'd solve the duplicate issue. I'd rather add more content and do more worldbuilding though. Also an excuse to improve stuff that is almost always behind the scenes.

The SEO expert here says keeping Teothe related content in the site, with its deities etc. is the best. You can keep npc generator there as well since it is Teothe related. Quest idea is not, so, better if it is separate.

He said the same thing about calculators, instead of having them on a different site, have them on Teothe and improve SEO. If there is enough to make a calculator site, make so.

Incoming new branch then.
