### ISSUE TITLE
Wrong backlinks

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#110]
![image](https://github.com/user-attachments/assets/7b7289df-093a-46bb-a8dc-48df52afd83b)

**Comment by ozgurozbek** [comment]
/races have been swapped to /species. Those pages probably use a component or something else that still uses the old url

**Comment by kutagorn** [comment]
I ll start working on this starting next week.

**Comment by ozgurozbek** [comment]
Actually with the new crawls this might've changed. Let me make sure first.

**Comment by ozgurozbek** [comment]
This just needs more time and traffic to be fixed for those pages.
