### ISSUE TITLE
Convert Navbar on Mobile to Hamburger only

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#112]
![image](https://github.com/user-attachments/assets/f72f40c8-8a0b-4694-8f31-b0e14e258891)

Just put everything to hamburger please. If you can float it to the right that'd be great as well.

Also see if its twitching, a weird bug; see live on mobile.

**Comment by kutagorn** [comment]
I will handle this bug.

**Comment by kutagorn** [comment]
I was sick for the last couple of weeks, I will try to finish this one ASAP, sorry for the wait.
