### ISSUE TITLE
Mobile map legend button's are not responsive.

### ISSUE THREAD

**Issue by kutagorn** [ozgurozbek/teothe#121]
As the title says, on the map legends page, the bottom buttons are not responsive.

I attached some screenshots about the issue.

![image](https://github.com/user-attachments/assets/5b649808-bca7-4c16-ac0d-e4ae5d25370a)
![image](https://github.com/user-attachments/assets/72c36932-76e4-42d9-a392-750a42c5118d)

- [ ] #123

**Comment by ozgurozbek** [comment]
Good catch. On it

**Comment by ozgurozbek** [comment]
@kutagorn please review PR #122
