### ISSUE TITLE
Responsiveness after Navbar changes

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#43]
There are small changes to be made on the following pages to fix mobile responsiveness.

- [x] **Books** opened on mobile don't have their close button or on screen controls when it comes to responsiveness.
- [x] **Languages dropdown** needs a scrollbar
- [x] Some **Tables** need a horizontal scrollbar
- [x] **Tools** requires a similar fix as above
- [x] **Calendar controls** is unresponsive, needs definitions for screen sizes or percentages
- [x] **Map Legend** icons are unresponsive

**Comment by god-hephaestus** [comment]
All done
