### ISSUE TITLE
Map Legend network load

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#45]
Map Legend images should be moved to the frontend repo to reduce network load since we've used Base64 to post images. We need to do what we did with the pages for races or deities.

**Comment by ozgurozbek** [comment]
As discussed, you'd need to pull the Base64 network response for each image, minify, and update the frontend to not use the backend @kutagorn. LMK, if you need anything else, I'm already assigned to this and following.

You can find each in your network panel on the dev console like this.
![image](https://github.com/ozgurozbek/teothe/assets/43455645/c1565c9d-1260-43e2-af6b-b6cf5cc86e40)

If you want the source, they are on the backend repo, hmu.

You can use https://tinypng.com/ to minify images.

**Comment by kutagorn** [comment]
On it boss.
