### ISSUE TITLE
Mobile GoUp Caret is not vertically centered.

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#65]
Check on your mobile device or see below. I couldn't recreate this on PC, but all PWA, landscape and vertical orientations have this issue.

![image](https://github.com/ozgurozbek/teothe/assets/43455645/40be8f80-6945-4140-b30d-5e13061ebcf4)
![image](https://github.com/ozgurozbek/teothe/assets/43455645/442bfc3c-3aa4-453b-9245-2b74db952e23)

**Comment by ozgurozbek** [comment]
See branch [`unique-routes`](https://github.com/ozgurozbek/teothe/tree/unique-routes)

**Comment by ozgurozbek** [comment]
![image](https://github.com/ozgurozbek/teothe/assets/43455645/cdc72bb1-88d9-45ee-be6e-81a89153ab90)

Also has the same issue on Safari and Mac computers

**Comment by kutagorn** [comment]
On it boss
