### ISSUE TITLE
Add Generators, Quest Idea & NPC

### ISSUE THREAD

**Issue by god-hephaestus** [ozgurozbek/teothe#71]
Quest idea generator should be tied to teothe to increase traffic. You should probably also add some sort of advertising thing.

**Comment by ozgurozbek** [comment]
Fair point. No need to have 2 apps for this. Not sure how much traffic it'd redirect but it'd be good for teothe overall! On it.

**Comment by ozgurozbek** [comment]
See branch [`generators`](https://github.com/ozgurozbek/teothe/tree/generators) for reference.

**Comment by ozgurozbek** [comment]
![image](https://github.com/ozgurozbek/teothe/assets/43455645/081fd300-22ac-4e38-823e-a4022d442ce0)

So crazy that formatting our stuff imports NPCs to FGU as simple as this.

**Comment by ozgurozbek** [comment]
![image](https://github.com/ozgurozbek/teothe/assets/43455645/f73ae07b-04ac-43c0-bce3-59a59c44b63b)

Can't see further immediate updates to this. Let's just see how things play out.
