### ISSUE TITLE
Moon images fail to load when Next/Image

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#72]
![image](https://github.com/ozgurozbek/teothe/assets/43455645/4a37bc7b-17ad-4e64-b13c-207ce1d96bbd)

**Comment by god-hephaestus** [comment]
works fine in my run dev so I can't fix the issue

**Comment by ozgurozbek** [comment]
See 2f24c2eaf1432f61b42152c5954ee33163216025 @god-hephaestus. Fixed.
