### ISSUE TITLE
Implement Achievements page

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#77]
![image](https://github.com/ozgurozbek/teothe/assets/43455645/0b2140fb-73a3-419b-9dd2-89d05152b1f8)

Could you implement the achievements page from our Excel file? We want it to be intractable. [Icons can be found here, for example trophy](https://game-icons.net/search.html?q=trophy&idx=icons&p=0).

**Comment by kutagorn** [comment]
I pushed two commits today, first push was a massive code optimization and memo addition to our page so it does not render everytime. With this addition page is 1400% faster. (and It will not upset our db provider)
second one was the addition of sorting for the leaderboard. so Now our todolist looks like;
(~~)1- Sort table according to item ids in achievements.json(~~)
2- Update leaderboard, maybe make it a modal and toggle it with a button?
3 - Update checkbox styling
&& - Below are massive changes that is going to take massive brain, spirit and mental power.
Good to have todolist
4 - Achievemen details;
5 - User Profilleri ile integration

**Comment by kutagorn** [comment]
Only 4 and 5 remains, after some though they really need some dev. time, they need to be separete tasks, can you please open new issue's for both of them and explain in detail what do you want ?

**Comment by ozgurozbek** [comment]
Reopened, branch is not merged to master yet.

Thanks for keeping the issue updated, you can in the future use a markdown checklist. I've edited some comments for readability.

**Comment by ozgurozbek** [comment]
> Only 4 and 5 remains, after some though they really need some dev. time, they need to be separete tasks, can you please open new issue's for both of them and explain in detail what do you want ? 

4 needs to be embedded after 5, and 5 is waiting for the aws branch. Don't worry about these yet 👍

**Comment by ozgurozbek** [comment]
Any updates on this? Your hooks had problems last I checked the branch and there are no new pushes @kutagorn. If stuck let us know 😄

**Comment by kutagorn** [comment]
Sorry for the lack of presence; I have been quite sick and on the road, so I have not been able to work on the project for a while. I am back and well, and I hope to work on this project again from next week. I'll keep the team updated and reach out if I encounter any issues (which is likely). Thank you for your understanding
