### ISSUE TITLE
Add guilds to the website

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#88]
These regularly get updated, so having them as a component page like /deities with some images for their logos and another column for where their HQ is could be useful.

**Comment by ozgurozbek** [comment]
@kutagorn Any updates on this? If you are busy I can take a look.

**Comment by kutagorn** [comment]
I am and was busy, but my next week seems to be free so If it's not urgent I can take a look next week.

**Comment by ozgurozbek** [comment]
No urgency, take your time. Please name your branch with the issue name, such as guilds-to-website.11.07.2024, 17:35, "Kutay Can Kaynak" ***@***.***>:
I am and was busy, but my next week seems to be free so If it's not urgent I can take a look next week.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- With all due respect,Ozgur Ozbek

**Comment by ozgurozbek** [comment]
I need information from players whether this'd be useful or not during character creation, but they can handle this request with their DM and it'll be easier for everyone, especially the campaign or player backstory requires something custom that is NOT on the website. Not having it makes the world richer imo. Been stale for too long, closed.
