### ISSUE TITLE
Class no-scrollbar doesn't work on Languages and QuickNPC dropdown

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#97]
I've added the ability to scroll these dropdowns. They use the browser's native look, whereas we have a custom one in our calendar area. This is also using the thin variant.

![image](https://github.com/user-attachments/assets/c1ceae0d-1a26-4a84-b684-f3d875a4df0e)

I honestly was not expecting it to work (and it didn't), but having a scrollbar similar to the ones we have in the calendar would be nice.

![image](https://github.com/user-attachments/assets/c6ae6c2f-20bb-4007-b7a2-16fa6110a64b)

**Comment by ozgurozbek** [comment]
@god-hephaestus Do you mind fixing this when free? You added the feature to the calendar as well IIRC.

**Comment by god-hephaestus** [comment]
Sure, tomorrow I'll use this as my tutorial for issues, commits, pull requests, etc to the new team. 

great timing tbh.

**Comment by ozgurozbek** [comment]
Great news. Feel free to close the issue if you see it working with the commit message as well!

**Comment by god-hephaestus** [comment]
Solved. I also took the liberty to change the scroll thumb's color. Let me know what you think. (don't actually touch the issue I need it as a tutorial later)
![{510251CE-E500-4BF8-BA96-6528F4298577}](https://github.com/user-attachments/assets/e4054d3c-2311-4398-ae37-9877c3707233)
![{032E8985-EEBC-481F-BFFE-45EE9E26D178}](https://github.com/user-attachments/assets/02c2a2cd-361a-46b5-bedc-0921a2a7a84c)
