### ISSUE TITLE
npc-generator when updated needs this repo to clear its build cache

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#98]
I've no idea how to simplify this, as I intend to improve the npc generator. I don't want to add the `^` to the `package.lock` file either, but that might be the only solution. Can you guys also take a look, I'm open to ideas?

@god-hephaestus @kutagorn @hazalmaslan

**Comment by god-hephaestus** [comment]
Not sure how to approach that, but might as well add some listeners to different buttons/filters to see what people click. This needs SEO though.


@ozgurozbek mind opening the issues?

**Comment by ozgurozbek** [comment]
We can keep track of it in NextJS, _there's a library for that_. Let me sit on the idea for a while.

**Comment by ozgurozbek** [comment]
> Not sure how to approach that, but might as well add some listeners to different buttons/filters to see what people click. This needs SEO though.
> 
> @ozgurozbek mind opening the issues?

Not too big on this at the time, sorry.

**Comment by ozgurozbek** [comment]
This issue is not the SEO issue. This video somewhat explains the problem https://www.youtube.com/watch?v=dwd6uiucmIY. We definitely can't add `npm update` to the pipeline though. I'm still looking at the best practices for this.
